version: '3.7'

services: 
  api:
    image: node:erbium-alpine
    depends_on: 
      - mongo
    command: npm run dev
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    networks: 
      my-network:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks: 
      my-network:

networks: 
  my-network: 
    name: my-network